
version: '3.8'

services:
  newshub:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - newshub
